### ISSUE TITLE
Mistake in k-means

### ISSUE THREAD

**Issue by emmakarolina** [TuomoNieminen/Helsinki-Open-Data-Science#1]
Chapter 3:

The usage of `dist()`-function needs to be removed from k-means chapters, because kmeans-function already calculates distances.

**Comment by mantypet** [comment]
There was an introductory exercise about euclidean distances, so I left that there for now, but added a comment that this is just to get a hang of things. Use of dist() function has been removed from the K-means exercises themselves with an added note that the kmeans-function calculates the distances automagically.
